### ISSUE TITLE
Need to write  helpToolStripMenuItem_Click method.

### ISSUE THREAD

**Issue by shawnkoon** [shawnkoon/CS_ClockInProg#2]
Need to Write Logics for
 `private void helpToolStripMenuItem_Click(object sender, EventArgs e)` 

Some of the Things to Consider.

> It Needs to show help message about how to use the program.

Suggestion.

> Use MessageBox. (Recommand reading How to Use this If don't know).
> ex) MessageBox.show("Hello! welcome to .... \nThis is how to use....","The title of the message box");

**Comment by darcikhey27** [comment]
Let's work on the program functionality first, then later we can work on the about and how-to sections
