### ISSUE TITLE
Need to wrtie  aboutProgramToolStripMenuItem_Click method.

### ISSUE THREAD

**Issue by shawnkoon** [shawnkoon/CS_ClockInProg#3]
Need to Write Logics for
 `private void aboutProgramToolStripMenuItem_Click(object sender, EventArgs e)` 

Some of the Things to Consider.

> It Needs to show all the Contributers' Names As well as Program's version, language used and ETC...

Suggestion.

> Use MessageBox. (Recommand reading How to Use this If don't know).

**Comment by darcikhey27** [comment]
<h3>On it </h3>
